#Upgrade Statuses
#Tue Dec 03 20:30:34 KST 2024
attack_LevelCount=1
ship_shoot360=false
speed_LevelCount=1
bullet_num=1
bullet_LevelCount=0
attack_speed=600
bullet_damage=1
bullet_speed=10
Coin_LevelCount=1
coin_acquisition_multiplier=1.0
movement_speed=3.5
